[project]
name = "knowledge-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Luciano Teixeira", email = "luciano.teixeiras@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.5.0",
    "faster-whisper>=1.2.1",
    "pypdf>=6.17.0",
    "rich>=15.0.0",
]

[project.scripts]
knowledge-extractor = "knowledge_extractor.cli:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
